/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CountryInfo, University, ChecklistItem, SuccessStory } from './types';

export const COUNTRIES: CountryInfo[] = [
  {
    id: 'usa',
    name: 'United States',
    flag: '🇺🇸',
    costOfLiving: '$$$',
    avgTuition: '$25,000 - $55,000 / Yr',
    visaTime: '3 - 6 Weeks',
    workPermit: 'OPT: 12-36 Months (STEM)',
    successRate: 94.5,
    keyIntakes: ['September (Fall)', 'January (Spring)'],
    popularPrograms: ['Computer Science', 'MBA', 'Data Analytics', 'Biomedical Engineering'],
    universityCount: 250,
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    costOfLiving: '$$$',
    avgTuition: '£16,000 - £35,000 / Yr',
    visaTime: '2 - 3 Weeks',
    workPermit: 'Graduate Route: 24 Months',
    successRate: 98.1,
    keyIntakes: ['Sept/Oct (Primary)', 'Jan/Feb (Secondary)'],
    popularPrograms: ['Finance & Accounting', 'Law', 'Artificial Intelligence', 'Public Health'],
    universityCount: 160,
  },
  {
    id: 'canada',
    name: 'Canada',
    flag: '🇨🇦',
    costOfLiving: '$$',
    avgTuition: 'CAD $18,000 - $38,000 / Yr',
    visaTime: '4 - 12 Weeks',
    workPermit: 'PGWP: Up to 36 Months',
    successRate: 92.8,
    keyIntakes: ['September', 'January', 'May (Limited)'],
    popularPrograms: ['Software Engineering', 'Supply Chain Management', 'Business Analytics', 'Civil Engineering'],
    universityCount: 96,
  },
  {
    id: 'australia',
    name: 'Australia',
    flag: '🇦🇺',
    costOfLiving: '$$$',
    avgTuition: 'AUD $22,000 - $45,000 / Yr',
    visaTime: '3 - 8 Weeks',
    workPermit: 'Temporary Graduate: 24-48 Months',
    successRate: 96.4,
    keyIntakes: ['February (Sem 1)', 'July (Sem 2)'],
    popularPrograms: ['Information Technology', 'Nursing', 'Data Science', 'Hospitality & Tourism'],
    universityCount: 43,
  },
  {
    id: 'germany',
    name: 'Germany',
    flag: '🇩🇪',
    costOfLiving: '$',
    avgTuition: '€0 - €3,000 / Yr (State Universities)',
    visaTime: '6 - 12 Weeks',
    workPermit: 'Job Seeker Visa: 18 Months',
    successRate: 95.2,
    keyIntakes: ['Winter (Oct)', 'Summer (April)'],
    popularPrograms: ['Mechanical Engineering', 'Automotive Engineering', 'Cybersecurity', 'Physics'],
    universityCount: 380,
  },
  {
    id: 'japan',
    name: 'Japan',
    flag: '🇯🇵',
    costOfLiving: '$$',
    avgTuition: '¥800,000 - ¥1,500,000 / Yr',
    visaTime: '4 - 8 Weeks',
    workPermit: 'Work Status: Unlimited (with employment contract)',
    successRate: 97.5,
    keyIntakes: ['April (Primary)', 'October (Secondary)'],
    popularPrograms: ['Robotics', 'International Relations', 'Game Design', 'Advanced Physics'],
    universityCount: 780,
  },
];

export const UNIVERSITIES: University[] = [
  // USA
  {
    id: 'harvard',
    name: 'Harvard University',
    country: 'usa',
    ranking: 'QS #4',
    city: 'Cambridge, MA',
    logoUrl: '🏛️',
    popularFields: ['MBA', 'Law', 'Computer Science'],
    minGpa: 3.8,
    minIelts: 7.5,
    avgTuitionYear: '$54,000',
    scholarshipGrantMax: '100% Need-based aid',
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    country: 'usa',
    ranking: 'QS #5',
    city: 'Stanford, CA',
    logoUrl: '☀️',
    popularFields: ['AI', 'Entrepreneurship', 'Mechanical Eng'],
    minGpa: 3.85,
    minIelts: 7.5,
    avgTuitionYear: '$56,000',
    scholarshipGrantMax: '90% Merit Fellowship',
  },
  {
    id: 'nyu',
    name: 'New York University',
    country: 'usa',
    ranking: 'QS #38',
    city: 'New York, NY',
    logoUrl: '🗽',
    popularFields: ['Finance', 'Film Production', 'Data Science'],
    minGpa: 3.4,
    minIelts: 7.0,
    avgTuitionYear: '$48,000',
    scholarshipGrantMax: '50% Dean\'s Scholarship',
  },

  // UK
  {
    id: 'oxford',
    name: 'University of Oxford',
    country: 'uk',
    ranking: 'QS #3',
    city: 'Oxford',
    logoUrl: '👑',
    popularFields: ['Philosophy', 'Computational Biology', 'Economics'],
    minGpa: 3.75,
    minIelts: 7.5,
    avgTuitionYear: '£31,000',
    scholarshipGrantMax: 'Clarendon Full Funding',
  },
  {
    id: 'ucl',
    name: 'University College London',
    country: 'uk',
    ranking: 'QS #9',
    city: 'London',
    logoUrl: '🏛️',
    popularFields: ['Architecture', 'Neuroscience', 'Management'],
    minGpa: 3.3,
    minIelts: 7.0,
    avgTuitionYear: '£26,000',
    scholarshipGrantMax: '70% Commonwealth Grant',
  },

  // Canada
  {
    id: 'toronto',
    name: 'University of Toronto',
    country: 'canada',
    ranking: 'QS #21',
    city: 'Toronto, ON',
    logoUrl: '🍁',
    popularFields: ['Machine Learning', 'Public Health', 'Business Info Systems'],
    minGpa: 3.2,
    minIelts: 6.5,
    avgTuitionYear: 'CAD $42,000',
    scholarshipGrantMax: 'Lester B. Pearson Full Ride',
  },
  {
    id: 'ubc',
    name: 'University of British Columbia',
    country: 'canada',
    ranking: 'QS #34',
    city: 'Vancouver, BC',
    logoUrl: '🌲',
    popularFields: ['Environmental Sciences', 'Finance', 'Mining Engineering'],
    minGpa: 3.1,
    minIelts: 6.5,
    avgTuitionYear: 'CAD $38,000',
    scholarshipGrantMax: 'CAD $20k Outstanding Internat.',
  },

  // Australia
  {
    id: 'melbourne',
    name: 'University of Melbourne',
    country: 'australia',
    ranking: 'QS #14',
    city: 'Melbourne, VIC',
    logoUrl: '🦘',
    popularFields: ['Veterinary Medicine', 'Law', 'Information Technology'],
    minGpa: 3.2,
    minIelts: 6.5,
    avgTuitionYear: 'AUD $41,000',
    scholarshipGrantMax: '50% Global Merit Award',
  },
  {
    id: 'sydney',
    name: 'University of Sydney',
    country: 'australia',
    ranking: 'QS #19',
    city: 'Sydney, NSW',
    logoUrl: '⛵',
    popularFields: ['Biomedicine', 'Aerospace Eng', 'Digital Marketing'],
    minGpa: 3.0,
    minIelts: 6.5,
    avgTuitionYear: 'AUD $39,500',
    scholarshipGrantMax: 'AUD $25k Vice-Chancellor Grant',
  },

  // Germany
  {
    id: 'tum',
    name: 'Technical University of Munich',
    country: 'germany',
    ranking: 'QS #37',
    city: 'Munich',
    logoUrl: '🥨',
    popularFields: ['Automotive Engineering', 'Cybersecurity', 'Informatics'],
    minGpa: 3.0,
    minIelts: 6.5,
    avgTuitionYear: '€0 (No Tuition)',
    scholarshipGrantMax: 'DAAD Full Monthly Stipend',
  },
  {
    id: 'heidelberg',
    name: 'Heidelberg University',
    country: 'germany',
    ranking: 'QS #87',
    city: 'Heidelberg',
    logoUrl: '🏰',
    popularFields: ['Medicine', 'Physics', 'Ancient History'],
    minGpa: 2.8,
    minIelts: 6.5,
    avgTuitionYear: '€3,000',
    scholarshipGrantMax: 'Deutschlandstipendium (€300/mo)',
  },

  // Japan
  {
    id: 'tokyo',
    name: 'University of Tokyo',
    country: 'japan',
    ranking: 'QS #28',
    city: 'Tokyo',
    logoUrl: '🌸',
    popularFields: ['Artificial Intelligence', 'Robotics', 'Quantum Computing'],
    minGpa: 3.5,
    minIelts: 7.0,
    avgTuitionYear: '¥820,000',
    scholarshipGrantMax: 'MEXT Full Government Scholarship',
  },
  {
    id: 'kyoto',
    name: 'Kyoto University',
    country: 'japan',
    ranking: 'QS #46',
    city: 'Kyoto',
    logoUrl: '⛩️',
    popularFields: ['Chemical Science', 'East Asian Studies', 'Astrophysics'],
    minGpa: 3.3,
    minIelts: 6.5,
    avgTuitionYear: '¥820,000',
    scholarshipGrantMax: 'JASSO Monthly Grant Support',
  },
];

export const INITIAL_CHECKLIST: ChecklistItem[] = [
  {
    id: 'docs-transcript',
    name: 'Official Academic Transcripts',
    description: 'Scanned official mark sheets from high school or current undergraduate degree.',
    category: 'academic',
    required: true,
    uploaded: false,
  },
  {
    id: 'docs-sop',
    name: 'Statement of Purpose (SOP)',
    description: 'A 1000-word essay mapping your global academic motivations, background, and career aspirations.',
    category: 'academic',
    required: true,
    uploaded: false,
  },
  {
    id: 'docs-lor',
    name: 'Letters of Recommendation (LORs)',
    description: 'At least two recommendation letters from academic advisors or professional mentors.',
    category: 'academic',
    required: true,
    uploaded: false,
  },
  {
    id: 'docs-eng',
    name: 'Language Proficiency Score Sheet',
    description: 'Your IELTS, TOEFL, or PTE test report demonstrating language competencies.',
    category: 'academic',
    required: true,
    uploaded: false,
  },
  {
    id: 'docs-passport',
    name: 'National Passport Bio-Page',
    description: 'Scanned page showing date of birth, photo, passport number, validity period.',
    category: 'identity',
    required: true,
    uploaded: false,
  },
  {
    id: 'docs-cv',
    name: 'Professional CV / Academic Resume',
    description: 'An updated summary outlining academic grades, project achievements, and work experience.',
    category: 'personal',
    required: false,
    uploaded: false,
  },
];

export const SUCCESS_STORIES: SuccessStory[] = [
  {
    id: 'story-1',
    studentName: 'Zainab Ahmed',
    originCountry: 'UAE',
    destinationCountry: 'United Kingdom',
    universityName: 'University of Oxford',
    program: 'MSc in Artificial Intelligence',
    scholarshipValue: '£42k (Clarendon Scholar)',
    imageSeed: 'female_student1',
    quote: 'The academic assessment team analyzed my transcripts, polished my Statement of Purpose, and guided me step-by-step through the prestigious Clarendon application framework. I couldn\'t have navigated Oxford alone!',
  },
  {
    id: 'story-2',
    studentName: 'Kenji Sato',
    originCountry: 'Japan',
    destinationCountry: 'United States',
    universityName: 'Stanford University',
    program: 'BSc in Computer Science',
    scholarshipValue: '$56,000 Merit Fellowship',
    imageSeed: 'male_student1',
    quote: 'EduCompass streamlined everything for me, translating requirements and organizing my recommendation submissions seamlessly. Landing this tech fellowship in Silicon Valley is a dream turned reality!',
  },
  {
    id: 'story-3',
    studentName: 'Larissa Gomez',
    originCountry: 'Brazil',
    destinationCountry: 'Germany',
    universityName: 'Technical University of Munich',
    program: 'MSc in Mechanical Engineering',
    scholarshipValue: '100% Tuition Waiver + DAAD',
    imageSeed: 'female_student2',
    quote: 'Tuition-free higher education was my goal, but the complex German visa process and DAAD stipend documentation was terrifying. Their specialist counseling saved me months of stress.',
  },
  {
    id: 'story-4',
    studentName: 'Rohan Sharma',
    originCountry: 'India',
    destinationCountry: 'Canada',
    universityName: 'University of Toronto',
    program: 'Master of Business Analytics',
    scholarshipValue: 'CAD $25,000 Outstanding Award',
    imageSeed: 'male_student2',
    quote: 'From choosing the perfect program to drafting a foolproof study permit file, they treated my dream as their own. I highly recommend them for any prospective global thinker.',
  },
];

export const MOCK_BOT_RESPONSES: { keywords: string[]; answer: string }[] = [
  {
    keywords: ['scholarship', 'scholar', 'fund', 'free', 'money', 'cost'],
    answer: "Our consultancy specializes in international grants! By scoring high (GPA > 3.5 & IELTS > 7.0), you unlock maximum merit opportunities. Countries like Germany offer tuition-free instruction, while Australia/US feature automatic Dean's merit grants ranging from 20% up to full rides. Use our integrated Scholarship Calculator in the dashboard to see your tailored projection!",
  },
  {
    keywords: ['visa', 'permit', 'pass', 'stay', 'success'],
    answer: "International study visas require accurate financial backing evidence, a clean study plan matching your past degree, and unconditional admission letters. Canada uses the SDS framework (fast), Germany runs Blocked Accounts, and the UK utilizes the CAS letter. We boast a stellar 98.2% visual visa success score because our documents audit is exhaustive!",
  },
  {
    keywords: ['gpa', 'transcript', 'grades', 'score', 'average'],
    answer: "A GPA above 3.0 out of 4.0 (approx. 75%+) qualifies you safely for leading international universities. But don't worry—if your GPA is between 2.5 and 2.9, pathway study modes and pre-master configurations exist! Let's schedule a dedicated folder evaluation to identify target institutions.",
  },
  {
    keywords: ['ielts', 'toefl', 'english', 'test', 'language', 'pte'],
    answer: "Generally, top global bachelor and master plans seek an IELTS of 6.5 (minimum 6.0 in each band) or a TOEFL rating of 80+. However, if your score is lower, some schools issue 'Conditional offers' linked to pre-sessional grammar program integrations. Check your score against our Calculator tool to see matching options!",
  },
  {
    keywords: ['apply', 'start', 'consult', 'booking', 'help', 'contact'],
    answer: "You've landed at the right portal! You can submit an official application directly inside the 'Apply Now' module on this interface. Once sent, an expert regional advisor will review your goals and schedule a live deep-dive video session completely free of charge.",
  },
  {
    keywords: ['germany', 'munich', 'tum', 'tuition'],
    answer: "Germany offers a highly popular academic pathway due to excellent state universities being practically tuition-free (except for standard €150-€350 administration fees per semester). English-medium courses are plentiful, but slots are extremely competitive! You'll need to open an official German Blocked Academic Money account (approx. €11,900) to secure your student visa.",
  },
];
